# Generated by Django 6.1 on 2026-08-25 14:26

import apps.webhooks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models.default_event_id, max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models.default_subscription_id, max_length=64, primary_key=True, serialize=False)),
                ('destination_url', models.TextField()),
                ('event_types', models.JSONField(default=list)),
                ('signing_secret_encrypted', models.TextField()),
                ('destination_secret_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default=apps.webhooks.models.default_delivery_id, max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('succeeded', 'Succeeded'), ('dead', 'Dead')], default='pending', max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=4)),
                ('next_attempt_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_token', models.CharField(blank=True, max_length=64, null=True)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.apikey')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.event')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttemptLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.delivery')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_attempt_number_per_delivery')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['api_key', 'created_at'], name='webhooks_ev_api_key_f82408_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('api_key', 'idempotency_key'), name='unique_event_idempotency_per_api_key'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['api_key', 'created_at'], name='webhooks_su_api_key_135471_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['api_key', 'is_active'], name='webhooks_su_api_key_57bf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhooks_de_status_c8abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['subscription', 'created_at'], name='webhooks_de_subscri_ce31ed_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['event'], name='webhooks_de_event_i_3c5643_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'event'), name='unique_delivery_per_subscription_event'),
        ),
    ]
